#!/bin/bash
if [ $# -eq 0 ]; then
	echo "do Compile <cpp filename without extension>"
	exit 0
fi
rm -rf "$1.e"
g++ -g -std=c++11 -fPIC -I./include -I${ROOTSYS}/include "$1.cpp" -L${ROOTSYS}/lib `root-config --libs` -lRIO -lGeom -lGraf -lGpad  -lHist -lEG -lPhysics -lMathMore -lm -o "$1.e"
